### ISSUE TITLE
Just quick

### ISSUE THREAD

**Issue by Khhs167** [programmerShourya/Password-helper#1]
U inviter me to an organisation, why?

**Comment by programmerShourya** [comment]
Yes man I am inviting pls join it

**Comment by Khhs167** [comment]
Well, i get to a 404 page tho

**Comment by programmerShourya** [comment]
Ok I would add you again close this issue when you would be added okay

**Comment by programmerShourya** [comment]
Did you try my password helper if so that's good

**Comment by programmerShourya** [comment]
Done again invitation accept it here https://github.com/CoderHubs
